"""add publication date in CompetitionNews model

Revision ID: 36421f4bfd3c
Revises: 860d361b0031
Create Date: 2018-09-08 15:01:26.147623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36421f4bfd3c'
down_revision = '860d361b0031'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competition_news', sa.Column('publication_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competition_news', 'publication_date')
    # ### end Alembic commands ###
