"""add column for signup limits

Revision ID: 4679a960c1ec
Revises: 474447a9e13d
Create Date: 2018-09-13 00:47:02.042677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4679a960c1ec'
down_revision = '474447a9e13d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competition', sa.Column('limit', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competition', 'limit')
    # ### end Alembic commands ###
