"""add status indicating if school password is changed

Revision ID: 474447a9e13d
Revises: f3dae521fa4f
Create Date: 2018-09-12 16:34:37.648919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '474447a9e13d'
down_revision = 'f3dae521fa4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('status', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schools', 'status')
    # ### end Alembic commands ###
