"""fix relationship

Revision ID: 4ab5c7fc5e0f
Revises: be011eb18c7d
Create Date: 2018-09-12 15:25:12.273578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ab5c7fc5e0f'
down_revision = 'be011eb18c7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competition_signup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=100), nullable=True),
    sa.Column('student_class', sa.String(length=100), nullable=True),
    sa.Column('instructor1', sa.String(length=100), nullable=True),
    sa.Column('instructor2', sa.String(length=100), nullable=True),
    sa.Column('signup_datetime', sa.DateTime(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competition.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schools_competition_signup',
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('competition_signup_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['competition_signup_id'], ['competition_signup.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], )
    )
    op.drop_table('schools_competition')
    op.drop_table('competition_sign_up')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competition_sign_up',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('student_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('student_class', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('instructor1', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('instructor2', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('competition_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('signup_datetime', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competition.id'], name='competition_sign_up_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('schools_competition',
    sa.Column('school_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('competition_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competition.id'], name='schools_competition_ibfk_1'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name='schools_competition_ibfk_2'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('schools_competition_signup')
    op.drop_table('competition_signup')
    # ### end Alembic commands ###
