"""add student2_* and instructor3 column

Revision ID: 740f57b096ef
Revises: 3652ac23b89d
Create Date: 2018-09-14 10:51:24.014181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '740f57b096ef'
down_revision = '3652ac23b89d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competition_signup', sa.Column('instructor3', sa.String(length=100), nullable=True))
    op.add_column('competition_signup', sa.Column('student2_class', sa.String(length=100), nullable=True))
    op.add_column('competition_signup', sa.Column('student2_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competition_signup', 'student2_name')
    op.drop_column('competition_signup', 'student2_class')
    op.drop_column('competition_signup', 'instructor3')
    # ### end Alembic commands ###
