"""school name should not be unique

Revision ID: 80aaa74de5be
Revises: 740f57b096ef
Create Date: 2018-11-02 16:27:00.466463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80aaa74de5be'
down_revision = '740f57b096ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='managers')
    op.drop_index('name', table_name='schools')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'schools', ['name'], unique=True)
    op.create_index('name', 'managers', ['name'], unique=True)
    # ### end Alembic commands ###
