"""add signup datetime in CompetitionSignUp model

Revision ID: 860d361b0031
Revises: 80254e296c32
Create Date: 2018-09-08 14:57:26.729817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '860d361b0031'
down_revision = '80254e296c32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competition_sign_up', sa.Column('signup_datetime', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competition_sign_up', 'signup_datetime')
    # ### end Alembic commands ###
