"""competition news should be stickable

Revision ID: b2713869b3a2
Revises: 36421f4bfd3c
Create Date: 2018-09-08 18:22:42.316205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2713869b3a2'
down_revision = '36421f4bfd3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competition_news', sa.Column('status', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competition_news', 'status')
    # ### end Alembic commands ###
