"""change maximum length of password column to 150

Revision ID: c3aa13fb1cf7
Revises: 57e0d34f355f
Create Date: 2018-09-09 15:09:00.771775

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3aa13fb1cf7'
down_revision = '57e0d34f355f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('managers', '_password',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=125),
               existing_nullable=False)
    op.alter_column('managers', 'type',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('schools', '_password',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=125),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schools', '_password',
               existing_type=sa.String(length=125),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('managers', 'type',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('managers', '_password',
               existing_type=sa.String(length=125),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
