"""remove unneccessary many to many table

Revision ID: f3dae521fa4f
Revises: 4ab5c7fc5e0f
Create Date: 2018-09-12 15:32:06.245129

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3dae521fa4f'
down_revision = '4ab5c7fc5e0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schools_competition_signup')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools_competition_signup',
    sa.Column('school_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('competition_signup_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['competition_signup_id'], ['competition_signup.id'], name='schools_competition_signup_ibfk_1'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name='schools_competition_signup_ibfk_2'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
